### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by lancergr**

### CODE REVIEW

**Comment by rikterbeek** [comment]
@lancergr what version of the Java Lib is it using ? Let's make sure it will use the new 1.7.0 release we are going to do.

**Comment by lancergr** [comment]
@rikterbeek having a greater version is always better but could you elaborate on what features of 1.7.0 do we need for this release ?

**Comment by rikterbeek** [comment]
@lancergr we need applicationInformation that will be included in version 1.7.0.

**Comment by rikterbeek** [comment]
@lancergr we released version 1.7.0 can you use this one ?

**Comment by lancergr** [comment]
> @lancergr we released version 1.7.0 can you use this one ?

done

**Pull request merged**
