### PR TITLE
[issue-42] Fixed problem with extending class from yacceleratorstorefront

### PR DESCRIPTION
**Pull request by maciek-marcinkowski**

### CODE REVIEW

**Comment by lancergr** [comment]
Hi @maciek-marcinkowski 
Thanks for the suggestion and the Pull Request!

Could you extend the de.hybris.platform.acceleratorstorefrontcommons.controllers.pages.checkout.steps.AbstractCheckoutStepController in this line:
https://github.com/Adyen/adyen-hybris/pull/43/files#diff-00e6ea8a2608f30e468945e3ef431d47R71

Regards,
Giorgos
Adyen

**Comment by maciek-marcinkowski** [comment]
OK, I can see while reformatting a code I removed the most significant part of fix. Is it ok right now? 

Regards,
Maciek

**Comment by lancergr** [comment]
Could you remove the Override annotation on line 124, since the placeOrder is not on the superclass?
https://github.com/Adyen/adyen-hybris/pull/43/files#diff-00e6ea8a2608f30e468945e3ef431d47R124

**Comment by maciek-marcinkowski** [comment]
Override removed

**Comment by lancergr** [comment]
Thanks @maciek-marcinkowski

**Pull request merged**
